name: coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  LINE_COVERAGE_REQ: 80

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Execute script to generate report
      run: ./scripts/code_coverage_analysis.sh

    - name: Publish badge JSON
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git fetch origin badges || git checkout --orphan badges
        git checkout badges
        mkdir ./.github/badges
        cp ./build/code-coverage/coverage-report/coverage-badge.json ./.github/badges/coverage-badge.json
        git add ./.github/badges/coverage-badge.json
        git commit -m "Update coverage badge" || echo "No changes"
        git push origin badges --force
